plugins {
    id 'net.minecraftforge.gradle' version '6.0.25'
}

group = 'com.example'
version = '1.0.0'
archivesBaseName = 'genshindownloader'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            workingDirectory project.file('run')
            mods { genshindownloader { source sourceSets.main } }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}

jar {
    manifest {
        attributes([
            "Specification-Title": "genshindownloader",
            "Specification-Vendor": "example",
            "Implementation-Title": project.name,
            "Implementation-Version": project.version
        ])
    }
}
